# Generated by Django 4.2.4 on 2023-08-23 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("vnom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vnoms",
            name="villes",
            field=models.CharField(
                choices=[("Oujda", "oujda"), ("fes", "fes"), ("casa", "casa")],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
